/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name  VARCHAR(100),
    date_of_birth  DATE,    
  	escape_attempts  INT,  	
  	neutered  BOOLEAN NOT NULL,
  	weight_kg  DECIMAL,
    PRIMARY KEY (id)
);

ALTER TABLE animals ADD COLUMN species VARCHAR(100);

CREATE TABLE owners(
  id INT GENERATED BY DEFAULT AS IDENTITY,
  full_name VARCHAR(100),
  age INT,
  PRIMARY KEY (id)
); 

CREATE TABLE species(
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100),
  PRIMARY KEY (id)
); 

ALTER TABLE animals DROP COLUMN species;

ALTER TABLE animals ADD species_id INT;

ALTER TABLE animals ADD CONSTRAINT species_fk FOREIGN KEY (species_id) REFERENCES species(id);

ALTER TABLE animals ADD owner_id INT;

ALTER TABLE animals ADD CONSTRAINT owners_fk FOREIGN KEY (owner_id) REFERENCES owners(id);

CREATE TABLE vets (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100),
  age INT,
  date_of_graduation DATE
);

CREATE TABLE specializations (
  vets_id INT REFERENCES vets(id),
  species_id INT REFERENCES species(id)
);

CREATE TABLE visits (
  vets_id INT REFERENCES vets(id),
  animals_id INT REFERENCES animals(id),
  date_of_visits DATE
);